<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="UKNHBVM0504" name="Test1" tests="1" failures="1" timestamp="13 Jan 2017 10:56:30 GMT" time="227.886" errors="0">
  <testcase name="testNQATestng" time="226.9" classname="com.landg.lqa.testflow.TestFlow02">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="-1">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: -1
	at com.landg.lqa.testflow.TestFlow02.testNQATestng(TestFlow02.java:455)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- testNQATestng -->
</testsuite> <!-- Test1 -->
